settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: avzeus-backend
  path: .
  commands:
    build:
      status: true
      method: go build -o .realize/main ./cmd/main.go
    run:
      status: true
      method: ./.realize/main
  watcher:
    extensions:
    - go
    paths:
    - /
    ignore:
      paths:
      - .git
      - .realize
