FROM golang:1.15.0-alpine3.12

WORKDIR /go/src/github.com/souhub/avzeus-backend

RUN apk add --no-cache \
    alpine-sdk \
    git \
    && go get github.com/oxequa/realize

ENV DB_USER souhub

ENV DB_PASS devpass

ENV DB_PROTOCOL tcp

ENV DB_ENDPOINT mysql:3306

ENV DB_NAME avzeus

ENV CLOUD_STORAGE_PATH https://storage.googleapis.com/avzeus

# COPY . .

RUN go build cmd

EXPOSE 8000

CMD [ "realize", "start"]
# CMD ["go","run","cmd/main.go"]
